---
title: "Exercise 1.4 - Managing Your New Resources"
workshops: azure_infra_ansible
workshop_weight: 14
layout: lab
---

:icons: font
:imagesdir: /workshops/azure_infra_ansible/images
:variables_url: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html
:service_url: http://docs.ansible.com/ansible/service_module.html


= Exercise 1.4 - Managing Your New Resources

Congratulations!  You just wrote a playbook that allows you to create and manage Azure Infrastructure.
But what happens once that infrastructure is up? How do we manage and maintain it?

== Section 1 - Updating your host file

=== Step 1: Updating your host file
The first thing we are going to do is make some changes to the host file.

[source,bash]
----
cd ..
vi hosts
----

Inside of the host file we are going to be adding a new group and some variables to connect to your remote machine.

[source,bash]
----
localhost

[all:vars]
ansible_ssh_private_key_file=/home/{{< urifqdn_azure_login "student" >}}/.ssh/id_rsa
ansible_port=22
ansible_user={{< urifqdn_azure_login "student" >}}

[web]
{{< urifqdn_azure_vm "Student" "vm1" >}}
----

[NOTE]
We created a group for the systems that we named *web*. We also created some variables that all of the machines will use.
This is not the only place that we can place variables, to see more click link:{variables_url}[here].

== Section 2 - Ad Hoc Commands

For our first exercise, we are going to run some ad hoc commands to help you get a feel for how Red Hat Ansible Tower works.  Ansible ad hoc commands enable you to perform repeatable tasks on remote nodes, without having to write a playbook.  They are very useful when you simply need to do one or two tasks quickly and often, to many remote nodes.

=== Step 1: Test webhost response

Let's start with something basic - pinging a host.  The `ping` module tests the responsiveness of our web host.

[source,bash]
----
ansible web -i hosts -m ping
----

=== Step 2: Run a Linux command

Now let's see how we can run a Linux command and format the output, using the `command` module.


[source,bash]
----
ansible web -i hosts -m command -a "uptime" -o
----

=== Step 3: Review the setup module

Take a look at your web node's configuration.  The `setup` module displays Ansible facts (and a lot of them) about an endpoint.

[source,bash]
----
ansible web -i hosts -m setup
----

====
[NOTE]
Like many Linux commands, `ansible` allows for long-form options as well as short-form.  For example:

----
ansible web --module-name ping
----
is the same as running
----
ansible web -m ping
----
We are going to be using the short-form options throughout this workshop
====

{{< importPartial "footer/footer_azure.html" >}}
